language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# Install the dependencies of deb-pkg-tools before running the test suite.
# For more information about the nasty /dev/random hack, please see:
# https://github.com/travis-ci/travis-ci/issues/1913#issuecomment-33891474
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --yes dpkg-dev fakeroot lintian python-apt rng-tools
  - sudo rm -f /dev/random
  - sudo mknod -m 0666 /dev/random c 1 9
  - echo HRNGDEVICE=/dev/urandom | sudo tee /etc/default/rng-tools
  - sudo /etc/init.d/rng-tools restart
# Prepare to submit coverage statistics to coveralls.io.
install:
  - pip install coveralls
  - python setup.py install
# Run the test suite as root so that all tests run (even the `dangerous ones').
script:
  sudo "$VIRTUAL_ENV/bin/coverage" run --source=deb_pkg_tools setup.py test
# Submit coverage statistics to coveralls.io after successful runs.
after_success:
  coveralls
