sudo: required
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - scripts/install-on-travis.sh
script:
  - make check
  - make full-coverage
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
